import{a as h,i as L}from"./assets/vendor-DH9Qgoyn.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))i(s);new MutationObserver(s=>{for(const n of s)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function o(s){const n={};return s.integrity&&(n.integrity=s.integrity),s.referrerPolicy&&(n.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?n.credentials="include":s.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function i(s){if(s.ep)return;s.ep=!0;const n=o(s);fetch(s.href,n)}})();const y="https://furniture-store.b.goit.study/api",v={FURNITURES:"/furnitures",CATEGORIES:"/categories",ORDERS:"/orders",FEEDBACKS:"/feedbacks"},w=h.create({baseURL:y,headers:{"Content-Type":"application/json"}});async function d(e=1,t=10){try{return(await w.get(v.FURNITURES,{params:{page:e,limit:t}})).data}catch{return L.error({title:"Помилка",message:"Не вдалося завантажити меблі. Спробуйте пізніше.",position:"topRight",timeout:4e3}),null}}(()=>{const e=document.querySelector(".js-menu-container"),t=document.querySelector(".js-open-menu"),o=t.querySelector("use"),i=e.querySelectorAll(".nav-link, .mobile-order-btn"),s=()=>o.getAttribute("href").split("#")[0],n=()=>{const r=s();e.classList.remove("is-open"),t.setAttribute("aria-expanded",!1),o.setAttribute("href",`${r}#icon-burger`),t.setAttribute("aria-label","Перемикач мобільного меню"),document.body.classList.remove("no-scroll")},c=()=>{const r=s();e.classList.add("is-open"),t.setAttribute("aria-expanded",!0),o.setAttribute("href",`${r}#icon-close`),t.setAttribute("aria-label","Закрити мобільне меню"),document.body.classList.add("no-scroll")},m=()=>{e.classList.contains("is-open")?n():c()};t.addEventListener("click",m),i.forEach(r=>{r.addEventListener("click",()=>{e.classList.contains("is-open")&&n()})}),document.addEventListener("keydown",r=>{r.key==="Escape"&&e.classList.contains("is-open")&&n()}),document.addEventListener("click",r=>{const f=e.classList.contains("is-open"),b=e.contains(r.target),g=t.contains(r.target);f&&!b&&!g&&n()}),window.matchMedia("(min-width: 1440px)").addEventListener("change",r=>{r.matches&&e.classList.contains("is-open")&&n()})})();let a=1,u=1;const l=document.querySelector(".pagination");async function p(e=d(a,8)){const t=document.querySelector(".products-list"),o=document.querySelector(".pagination");t.innerHTML="",o.innerHTML="";try{const i=await e,s=i.furnitures||i;u=Math.ceil(i.totalItems/8),s&&s.length?(s.forEach(n=>{const c=document.createElement("div");c.className="product-item",c.setAttribute("data-id",n._id),c.innerHTML=`
          <img src="${n.images[0]}" alt="${n.name}" class="img-card" width="100%" height="256px" />
          <p class="text-card">${n.name}</p>
          <div class="colors">
            ${n.color.map(m=>`<span class="color-one" style="background-color:${m};"></span>`).join("")}
          </div>
          <p class="text-card">${n.price} грн</p>
          <button class="btn btn-go-modal">Детальніше</button>
        `,t.appendChild(c)}),E(a),M()):t.innerHTML="<p>Товари не знайдені.</p>"}catch(i){console.error("Помилка завантаження товарів:",i),t.innerHTML="<p>Помилка завантаження товарів.</p>"}}function E(e){l.innerHTML="",l.innerHTML+=`
    <button class="btn-prev scroll">
      <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" class="icon">
        <path d="m313-440 224 224-57 56-320-320 320-320 57 56-224 224h487v80H313Z" />
      </svg>
    </button>
  `;for(let t=e;t<=Math.min(e+2,u);t++)l.innerHTML+=`
      <button class="page-number ${t===e?"focus":""}">${t}</button>
    `;e+2<u&&(l.innerHTML+='<span class="dtp">...</span>',l.innerHTML+=`<button class="page-number last">${u}</button>`),l.innerHTML+=`
    <button class="btn-next scroll">
      <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" class="icon">
        <path d="M647-440H160v-80h487L423-744l57-56 320 320-320 320-57-56 224-224Z" />
      </svg>
    </button>
  `}function M(){const e=document.querySelector(".btn-prev"),t=document.querySelector(".btn-next");a===1?e.classList.add("disabled"):e.classList.remove("disabled"),a>=u?t.classList.add("disabled"):t.classList.remove("disabled")}document.addEventListener("click",async e=>{if(e.target.closest(".page-number")){const t=e.target.closest(".page-number"),o=parseInt(t.textContent,10);isNaN(o)||(a=o,await p(d(a,8)))}e.target.closest(".btn-next")&&a<u&&(a++,await p(d(a,8))),e.target.closest(".btn-prev")&&a>1&&(a--,await p(d(a,8))),document.getElementById("furniture").scrollIntoView({behavior:"smooth",block:"center"})});document.addEventListener("DOMContentLoaded",()=>{p()});document.querySelectorAll(".faq-question").forEach(e=>{e.addEventListener("click",()=>{const t=e.nextElementSibling,o=e.querySelector("use"),i=t.style.display==="block";document.querySelectorAll(".faq-question").forEach(s=>{const n=s.nextElementSibling,c=s.querySelector("use");n.style.display="none",c.setAttribute("href","#down-arrow-alt")}),i||(t.style.display="block",o.setAttribute("href","#up-arrow-alt"))})});
//# sourceMappingURL=index.js.map
