import{a as L,i as v}from"./assets/vendor-DH9Qgoyn.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))c(s);new MutationObserver(s=>{for(const n of s)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function r(s){const n={};return s.integrity&&(n.integrity=s.integrity),s.referrerPolicy&&(n.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?n.credentials="include":s.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function c(s){if(s.ep)return;s.ep=!0;const n=r(s);fetch(s.href,n)}})();const w="https://furniture-store.b.goit.study/api",S={FURNITURES:"/furnitures",CATEGORIES:"/categories",ORDERS:"/orders",FEEDBACKS:"/feedbacks"},M=L.create({baseURL:w,headers:{"Content-Type":"application/json"}});async function d(e=1,t=10){try{return(await M.get(S.FURNITURES,{params:{page:e,limit:t}})).data}catch{return v.error({title:"Помилка",message:"Не вдалося завантажити меблі. Спробуйте пізніше.",position:"topRight",timeout:4e3}),null}}(()=>{const e=document.querySelector(".js-menu-container"),t=document.querySelector(".js-open-menu"),r=t.querySelector("use"),c=e.querySelectorAll(".nav-link, .mobile-order-btn"),s=()=>r.getAttribute("href").split("#")[0],n=()=>{const i=s();e.classList.remove("is-open"),t.setAttribute("aria-expanded",!1),r.setAttribute("href",`${i}#icon-burger`),t.setAttribute("aria-label","Перемикач мобільного меню"),document.body.classList.remove("no-scroll")},a=()=>{const i=s();e.classList.add("is-open"),t.setAttribute("aria-expanded",!0),r.setAttribute("href",`${i}#icon-close`),t.setAttribute("aria-label","Закрити мобільне меню"),document.body.classList.add("no-scroll")},m=()=>{e.classList.contains("is-open")?n():a()};t.addEventListener("click",m),c.forEach(i=>{i.addEventListener("click",()=>{e.classList.contains("is-open")&&n()})}),document.addEventListener("keydown",i=>{i.key==="Escape"&&e.classList.contains("is-open")&&n()}),document.addEventListener("click",i=>{const g=e.classList.contains("is-open"),h=e.contains(i.target),y=t.contains(i.target);g&&!h&&!y&&n()}),window.matchMedia("(min-width: 1440px)").addEventListener("change",i=>{i.matches&&e.classList.contains("is-open")&&n()})})();let o=1,l=1;const u=document.querySelector(".pagination"),f=document.querySelector(".btn-loadMore");async function p(e=d(o,8)){b();const t=document.querySelector(".products-list"),r=document.querySelector(".pagination");window.innerWidth<375&&(t.innerHTML="",r.innerHTML="");try{const c=await e;b();const s=c.furnitures||c;l=Math.ceil(c.totalItems/8),s&&s.length?(s.forEach(n=>{const a=document.createElement("div");a.className="product-item",a.setAttribute("data-id",n._id),a.innerHTML=`
          <img src="${n.images[0]}" alt="${n.name}" class="img-card" width="100%" height="256px" />
          <p class="text-card">${n.name}</p>
          <div class="colors">
            ${n.color.map(m=>`<span class="color-one" style="background-color:${m};"></span>`).join("")}
          </div>
          <p class="text-card">${n.price} грн</p>
          <button class="btn btn-go-modal">Детальніше</button>
        `,t.appendChild(a)}),E(o),q()):t.innerHTML="<p>Товари не знайдені.</p>"}catch(c){console.error("Помилка завантаження товарів:",c),t.innerHTML="<p>Помилка завантаження товарів.</p>"}}function E(e){u.innerHTML="",u.innerHTML+=`
    <button class="btn-prev scroll">
      <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" class="icon">
        <path d="m313-440 224 224-57 56-320-320 320-320 57 56-224 224h487v80H313Z" />
      </svg>
    </button>
  `;for(let t=e;t<=Math.min(e+2,l);t++)u.innerHTML+=`
      <button class="page-number ${t===e?"focus":""}">${t}</button>
    `;e+2<l&&(u.innerHTML+='<span class="dtp">...</span>',u.innerHTML+=`<button class="page-number last">${l}</button>`),u.innerHTML+=`
    <button class="btn-next scroll">
      <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" class="icon">
        <path d="M647-440H160v-80h487L423-744l57-56 320 320-320 320-57-56 224-224Z" />
      </svg>
    </button>
  `}function b(){document.querySelector(".loader").classList.toggle("visuallyhidden")}function q(){const e=document.querySelector(".btn-prev"),t=document.querySelector(".btn-next");o===1?e.classList.add("disabled"):e.classList.remove("disabled"),o>=l?t.classList.add("disabled"):t.classList.remove("disabled")}function x(){o>=l?f.style.display="none":f.style.display="inline"}document.addEventListener("click",async e=>{if(e.target.closest(".page-number")){const t=e.target.closest(".page-number"),r=parseInt(t.textContent,10);isNaN(r)||(o=r,await p(d(o,8)),setTimeout(()=>{document.querySelector(".products-list").scrollIntoView({behavior:"smooth",block:"nearest"})},300))}e.target.closest(".btn-next")&&o<l&&(o++,await p(d(o,8)),setTimeout(()=>{document.querySelector(".products-list").scrollIntoView({behavior:"smooth",block:"nearest"})},1e3)),e.target.closest(".btn-prev")&&o>1&&(o--,await p(d(o,8)),setTimeout(()=>{document.querySelector(".products-list").scrollIntoView({behavior:"smooth",block:"nearest"})},1e3))});f.addEventListener("click",async()=>{o<l&&(o++,await p(d(o,8)),x(),setTimeout(()=>{document.querySelector(".products-list").scrollIntoView({behavior:"smooth",block:"nearest"})},400))});document.addEventListener("DOMContentLoaded",()=>{p()});document.querySelectorAll(".faq-question").forEach(e=>{e.addEventListener("click",()=>{const t=e.nextElementSibling,r=e.querySelector("use"),c=t.style.display==="block";document.querySelectorAll(".faq-question").forEach(s=>{const n=s.nextElementSibling,a=s.querySelector("use");n.style.display="none",a.setAttribute("href","#down-arrow-alt")}),c||(t.style.display="block",r.setAttribute("href","#up-arrow-alt"))})});
//# sourceMappingURL=index.js.map
