import{a,i as l}from"./assets/vendor-sTcFRZSV.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const u="https://furniture-store.b.goit.study/api",d={FURNITURES:"/furnitures",CATEGORIES:"/categories",ORDERS:"/orders",FEEDBACKS:"/feedbacks"},p=a.create({baseURL:u,headers:{"Content-Type":"application/json"}});async function m(o=1,s=10){try{return(await p.get(d.FURNITURES,{params:{page:o,limit:s}})).data}catch{return l.error({title:"Помилка",message:"Не вдалося завантажити меблі. Спробуйте пізніше.",position:"topRight",timeout:4e3}),null}}(()=>{const o=document.querySelector(".js-menu-container"),s=document.querySelector(".js-open-menu"),r=s.querySelector("use"),i=o.querySelectorAll(".nav-link, .mobile-order-btn"),e=()=>r.getAttribute("href").split("#")[0],t=()=>{const n=o.classList.contains("is-open"),c=e();s.setAttribute("aria-expanded",!n),o.classList.toggle("is-open"),o.classList.contains("is-open")?(r.setAttribute("href",`${c}#icon-close`),s.setAttribute("aria-label","Закрити мобільне меню")):(r.setAttribute("href",`${c}#icon-burger`),s.setAttribute("aria-label","Перемикач мобільного меню")),document.body.classList.toggle("no-scroll")};s.addEventListener("click",t),i.forEach(n=>{n.addEventListener("click",()=>{o.classList.contains("is-open")&&t()})}),window.matchMedia("(min-width: 1440px)").addEventListener("change",n=>{if(!n.matches||!o.classList.contains("is-open"))return;const c=e();o.classList.remove("is-open"),s.setAttribute("aria-expanded",!1),r.setAttribute("href",`${c}#icon-burger`),s.setAttribute("aria-label","Перемикач мобільного меню"),document.body.classList.remove("no-scroll")})})();function f(o=m(1,8)){const s=document.querySelector(".products-list");o.then(r=>{const i=r.furnitures||r;i&&i.length?i.forEach(e=>{const t=document.createElement("div");t.className="product-item",t.setAttribute("data-id",e._id),t.innerHTML=`
                    <img src="${e.images[0]}" alt="${e.name}" class="img-card" width="100%" height="256px" />
                    <p class="text-card">${e.name}</p>
                    <div class="colors">
                      ${e.color.map(n=>`<span class="color-one" style="background-color:${n};"></span>`).join("")}
                    </div>
                    <p class="text-card">${e.price} грн</p>
                    <button class="btn btn-go-modal">Детальніше</button>
                `,s.appendChild(t)}):s.innerHTML="<p>Товари не знайдені.</p>"}).catch(r=>{console.error("Помилка завантаження товарів:",r),s.innerHTML="<p>Помилка завантаження товарів.</p>"})}addEventListener("DOMContentLoaded",()=>{f()});
//# sourceMappingURL=index.js.map
